development:
  adapter: postgresql
  encoding: unicode
  database: stash_buckets
  host: localhost
  pool: 5
  username: user
  password: "pass"

production:
  adapter: postgresql
  encoding: unicode
  database: stash_buckets
  host: localhost
  pool: 10
  username: user
  password: "pass"
