#!/usr/bin/env ruby

require './scripts/lib/auto_migrate.rb'

db_config = YAML.load_file('./config/database.yml')[ENV['RACK_ENV'] || 'development']
AutoMigrate.connect(db_config)

require './config/schema.rb'

