development:
  adapter: postgresql
  encoding: unicode
  database: stash_buckets_new
  host: localhost
  pool: 5
  username: dux
  password: "!Netlife"

production:
  adapter: postgresql
  encoding: unicode
  database: cleanpay
  host: localhost
  pool: 10
  username: sbprod
  password: sbprod1337